-- Order Entry (OE) Sales Analysis
-- Hansi mehsul kateqoriyasi en cox gelir getirir ve zaman uzre satis trendi
-- Oracle OE schema


-- 1. Kateqoriya uzre gelir
SELECT 
    c.CATEGORY_NAME,
    COUNT(DISTINCT oi.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oi.UNIT_PRICE * oi.QUANTITY) AS TOTAL_REVENUE
FROM OE.ORDER_ITEMS oi
JOIN OE.PRODUCT_INFORMATION p 
    ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN OE.CATEGORIES_TAB c 
    ON p.CATEGORY_ID = c.CATEGORY_ID
GROUP BY c.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;


-- 2. Ay uzre satis trendi
SELECT 
    TO_CHAR(o.ORDER_DATE, 'YYYY-MM') AS ORDER_MONTH,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oi.UNIT_PRICE * oi.QUANTITY) AS TOTAL_REVENUE
FROM OE.ORDERS o
JOIN OE.ORDER_ITEMS oi 
    ON o.ORDER_ID = oi.ORDER_ID
GROUP BY TO_CHAR(o.ORDER_DATE, 'YYYY-MM')
ORDER BY ORDER_MONTH;


-- 3. Kateqoriya + ay birlikde (Tableau ucun)
SELECT 
    c.CATEGORY_NAME,
    TO_CHAR(o.ORDER_DATE, 'YYYY-MM') AS ORDER_MONTH,
    SUM(oi.UNIT_PRICE * oi.QUANTITY) AS TOTAL_REVENUE
FROM OE.ORDERS o
JOIN OE.ORDER_ITEMS oi 
    ON o.ORDER_ID = oi.ORDER_ID
JOIN OE.PRODUCT_INFORMATION p 
    ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN OE.CATEGORIES_TAB c 
    ON p.CATEGORY_ID = c.CATEGORY_ID
GROUP BY c.CATEGORY_NAME, TO_CHAR(o.ORDER_DATE, 'YYYY-MM')
ORDER BY ORDER_MONTH, TOTAL_REVENUE DESC;
